version: '3'

services:
  kafka:
    image: wurstmeister/kafka:1.1.0
    container_name: kafka
    expose:
      - "9092"
    environment:
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    expose:
      - "2181"
  redis:
    image: redis:5.0.3
    container_name: redis
    expose:
      - "6379"
  skipper-server:
    image: springcloud/spring-cloud-skipper-server:latest
    container_name: skipper
    ports:
      - "7577:7577"
      - "9000-9010:9000-9010"
  mysql:
    image: mysql:5.7.25
    container_name: mysql
    environment:
      MYSQL_DATABASE: dataflow
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: rootpw
    ports:
      - "3306:3306"
